spring.application.name=rpgTest01
server.port=8089

# IBM i Connection
spring.datasource.url=jdbc:as400://pub400.com/--------------
spring.datasource.username=-----------
spring.datasource.password=-------------

spring.datasource.driver-class-name=com.ibm.as400.access.AS400JDBCDriver

# IMPORTANT: Fix HeadlessException
com.ibm.as400.access.AS400.guiAvailable=false
com.ibm.as400.access.AS400.noPrompt=true

# HikariCP Settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
# Fix HikariCP + JT400 compatibility issue
spring.datasource.hikari.connection-test-query=SELECT 1 FROM SYSIBM.SYSDUMMY1
spring.datasource.hikari.validation-timeout=3000

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# Development
gg.jte.development-mode=true
logging.level.com.example=DEBUG

HikariConfig config = new HikariConfig();
config.setJdbc4ConnectionTest(false);
config.setConnectionTestQuery("SELECT 1 FROM SYSIBM.SYSDUMMY1");